# Generated by Django 6.0.3 on 2026-03-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_id", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BHK1", "1 BHK"),
                            ("BHK2", "2 BHK"),
                            ("BHK3", "3 BHK"),
                            ("BHK4", "4 BHK"),
                            ("RK1", "1 RK"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activation_date", models.DateField()),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Independent House", "Independent House"),
                            ("Independent Floor", "Independent Floor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("Furnished", "Furnished"),
                            ("Semi-Furnished", "Semi-Furnished"),
                            ("Unfurnished", "Unfurnished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lease_type",
                    models.CharField(
                        choices=[
                            ("Family", "Family"),
                            ("Bachelor", "Bachelor"),
                            ("Company", "Company"),
                            ("Any", "Any"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pin_code", models.CharField(max_length=10)),
                ("bathroom", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("total_floor", models.IntegerField()),
                ("property_age", models.IntegerField()),
                ("property_size", models.IntegerField()),
                ("rent", models.IntegerField()),
                ("deposit", models.IntegerField()),
                ("gym", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("lift", models.BooleanField(default=False)),
                ("swimming_pool", models.BooleanField(default=False)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["rent"],
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Property",
                "verbose_name_plural": "Saved Properties",
                "unique_together": {("user", "property")},
            },
        ),
    ]
